#
# MPContainer compose (dev components)
#
version: '3.7'
services:
  # ------ mpcontainer-frontend ------
  frontend:
    volumes:
      - ./container-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./container-haproxy/checkhap.sh:/usr/local/bin/checkhap.sh:ro
      - ./container-haproxy/lua/:/usr/local/bin/lua/:ro
  # ------ mpcontainer-web ------
  backendweb:
    volumes:
      - ./container-web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container-web/html/:/usr/share/nginx/html:ro
  # ------ mpcontainer-shell ------
  adminmmpd:
    volumes:
      - webshelldata:/home/dj/data-vol/
  # ------ mpcontainer-pyapp ------
  mpcpyapp:
    environment:
      - env_mpcpyapp_dev=true
      - env_mpypyapp_envtest=docker_compose_dev
    volumes:
      - ./container-pyapp/:/pyapp:ro

volumes:
  webshelldata:
