#
# MPContainer compose (dev components)
#
version: '3.7'
services:
  # ------ mpcontainer-frontend ------
  frontend:
    build:
      context: ./container-haproxy/
      cache_from:
        - haproxy:2.2.13-alpine
    volumes:
      - ./container-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./container-haproxy/checkhap.sh:/usr/local/bin/checkhap.sh:ro
      - ./container-haproxy/lua/:/usr/local/bin/lua/:ro
  # ------ mpcontainer-web ------
  backendweb:
    build:
      context: ./container-web/
    volumes:
      - ./container-web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container-web/html/:/usr/share/nginx/html:ro
  # ------ mpcontainer-mpd ------
  backendmpd:
    build:
      context: ./container-mpd/
      cache_from:
        - debian:buster-slim
  # ------ mpcontainer-shell ------
  adminmmpd:
    build:
      context: ./container-shell/
      cache_from:
        - tsl0922/ttyd
    volumes:
      - webshelldata:/home/dj/data-vol/
  # ------ mpcontainer-pyapp ------
  mpcpyapp:
    build:
      context: ./container-pyapp/
      cache_from:
        - python:3-slim-buster
    ports:
      - "8888:8888"
    environment:
      - env_mpcpyapp_dev=true
      - env_mpypyapp_envtest=docker_compose_dev
    volumes:
      - ./container-pyapp/:/pyapp:ro

volumes:
  webshelldata: