version: '3.7'

services:

  # frontend public proxy
  # https://hub.docker.com/_/haproxy
  frontend:
    image: "haproxy:2.1-alpine"
    container_name: frontend
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
        reservations:
          cpus: '0.04'
          memory: 15M
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "3000:3001"
    networks:
      - webfrontnet
      - webfrontmpd
    depends_on:
      - backendweb
    labels:
      kompose.service.type: LoadBalancer

  # static web docs
  # https://hub.docker.com/_/nginx
  backendweb:
    image: nginx:1.18-alpine
    container_name: backendweb  
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
        reservations:
          cpus: '0.04'
          memory: 15M
    ports:
      - "8880"
    volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./webfiles:/usr/share/nginx/html:ro"
    networks:
      - webfrontnet

  # MPD server
  # https://hub.docker.com/_/debian
  backendmpd:
    build:
      context: .
      dockerfile: dockerfile-mpd
    container_name: backendmpd
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
        - "./music/db:/var/lib/mpd/music:ro"
    ports:
      - "6600"
      - "3123"
    networks:
      - webfrontmpd
      - mpdadmin

  # admin Web shell
  # https://hub.docker.com/r/tsl0922/ttyd
  adminmmpd:
    build:
      context: .
      dockerfile: dockerfile-shell
    container_name: adminmmpd
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    ports:
      - "7681"
    networks:
      - webfrontnet
      - mpdadmin

networks:
  webfrontnet:
    driver: bridge
  webfrontmpd:
    driver: bridge
  mpdadmin:
    driver: bridge