#
# MPContainer compose (for dev)
#
version: '3.7'
services:
  # ------ mpcontainer-frontend ------
  frontend:
    build:
      context: ./container-haproxy/
      cache_from:
        - haproxy:2.1-alpine
    container_name: frontend
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 15M
    volumes:
      - ./container-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    #cap_drop:
    #  - all
    #cap_add:
    #  - net_bind_service
    #  - chown
    #  - dac_override
    #  - setgid
    #  - setuid
    ports:
      - "3000:3001"
    networks:
      - webfrontnet
      - webfrontmpd
    depends_on:
      - backendweb
    labels:
      kompose.service.type: LoadBalancer
  # ------ mpcontainer-web ------
  backendweb:
    build:
      context: ./container-web/
    container_name: backendweb
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 15M
    ports:
      - "8880"
    volumes:
      - "./container-web/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./container-web/html/:/usr/share/nginx/html:ro"
    networks:
      - webfrontnet
  # ------ mpcontainer-mpd ------
  backendmpd:
    build:
      context: ./container-mpd/
      cache_from:
        - debian:buster-slim
    container_name: backendmpd
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
        - "./music/db:/var/lib/mpd/music:ro"
    cap_drop:
      - net_bind_service
      - chown
      - dac_override
    expose:
      - "6600"
      - "3123"
    networks:
      - webfrontmpd
      - mpdadmin
  # ------ mpcontainer-shell ------
  adminmmpd:
    build:
      context: ./container-shell/
      cache_from:
        - tsl0922/ttyd
    container_name: adminmmpd
    environment: 
        - TZ=UTC
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
      - webshelldata:/home/dj/data-vol/
    cap_drop:
      - fsetid
      - setgid
    expose:
      - "7681"
    networks:
      - webfrontnet
      - mpdadmin
  # ------ mpcontainer-pyapp ------
  mpcpyapp:
    build:
      context: ./container-pyapp/
      cache_from:
        - python:3-slim-buster
    container_name: pyapp
    environment: 
        - TZ=UTC
        # start in Dev mode
        - env_mpcpyapp_dev=true
    volumes:
      - "./container-pyapp/:/pyapp:ro"
    cap_drop:
      - net_bind_service
      - chown
      - dac_override
      - fsetid
      - setgid
    expose:
      - "8888"
    networks:
      - webfrontnet
      - mpdadmin

volumes:
  webshelldata:

networks:
  webfrontnet:
    driver: bridge
  webfrontmpd:
    driver: bridge
  mpdadmin:
    driver: bridge
