version: '3.7'

services:

  # public frontend proxy
  frontend:
    #image: "haproxy:2.1-alpine"
    build:
      context: .
      dockerfile: dockerfile-haproxy
      cache_from:
        - haproxy:2.1-alpine
    container_name: frontend
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
        reservations:
          cpus: '0.04'
          memory: 15M
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    cap_drop:
        - all
    cap_add:
        - net_bind_service
        - chown
        - dac_override
        - setgid
        - setuid
    ports:
      - "3000:3001"
    networks:
      - webfrontnet
      - webfrontmpd
    depends_on:
      - backendweb
    labels:
      kompose.service.type: LoadBalancer

  # static web docs backend
  backendweb:
    #image: nginx:1.18-alpine
    build:
      context: .
      dockerfile: dockerfile-web
      cache_from:
        - nginx:1.18-alpine
    container_name: backendweb
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
        reservations:
          cpus: '0.04'
          memory: 15M
    cap_drop:
      - all
    cap_add:
      - net_bind_service
      - chown
      - dac_override
      - setgid
      - setuid
    ports:
      - "8880"
    volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./webfiles/pub:/usr/share/nginx/html:ro"
    networks:
      - webfrontnet

  # MPD server
  backendmpd:
    build:
      context: .
      dockerfile: dockerfile-mpd
      cache_from:
        - debian:buster-slim
    container_name: backendmpd
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
        - "./music/db:/var/lib/mpd/music:ro"
    expose:
      - "6600"
      - "3123"
    networks:
      - webfrontmpd
      - mpdadmin

  # admin DJ Web shell
  adminmmpd:
    build:
      context: .
      dockerfile: dockerfile-shell
      cache_from:
        - tsl0922/ttyd
    container_name: adminmmpd
    environment: 
        - TZ=UTC
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
      - webshelldata:/home/dj/data-vol/
    expose:
      - "7681"
    networks:
      - webfrontnet
      - mpdadmin

  # mpc python app
  mpcpyapp:
    build:
      context: .
      dockerfile: dockerfile-pyapp
      cache_from:
        - python:3-slim-buster
    container_name: mpcpyapp
    environment: 
        - TZ=UTC
    volumes:
      - "./pyapp/:/pyapp:ro"
    expose:
      - "8888"
    networks:
      - webfrontnet
      - mpdadmin

volumes:
  webshelldata:

networks:
  webfrontnet:
    driver: bridge
  webfrontmpd:
    driver: bridge
  mpdadmin:
    driver: bridge
