#
# MPContainer compose
#
version: '3.7'
services:
  # ------ mpcontainer-frontend ------
  frontend:
    build:
      context: ./container-haproxy/
      cache_from:
        - haproxy:2.2-alpine
    container_name: haproxy
    restart: on-failure:5
    environment:
      - HAPX_US_PASS=leftthedefault2
    cap_drop:
      - setfcap
      - net_bind_service
      - dac_override
      - net_raw
    cap_add:
      - chown
      - dac_override
      - setgid
      - setuid
    ports:
      - "3000:3001"
    networks:
      - webfrontnet
      - webfrontmpd
    depends_on:
      - backendweb
    labels:
      kompose.service.type: LoadBalancer
  # ------ mpcontainer-web ------
  backendweb:
    build:
      context: ./container-web/
    container_name: backendweb
    restart: on-failure:5
    ports:
      - "8880"
    networks:
      - webfrontnet
  # ------ mpcontainer-mpd ------
  backendmpd:
    build:
      context: ./container-mpd/
      cache_from:
        - debian:buster-slim
    container_name: backendmpd
    restart: on-failure:5
    volumes:
        - ./music/db:/var/lib/mpd/music:ro
    cap_drop:
      - net_bind_service
      - chown
      - mknod
      - dac_override
    expose:
      - "6600"
      - "3123"
    networks:
      - webfrontmpd
      - mpdadmin
  # ------ mpcontainer-shell ------
  adminmmpd:
    build:
      context: ./container-shell/
      cache_from:
        - tsl0922/ttyd
    container_name: adminshell
    environment: 
        - TZ=UTC
    restart: on-failure:5
    cap_drop:
      - fsetid
      - setgid
      - mknod
      - net_bind_service
      - dac_override
    expose:
      - "7681"
    networks:
      - webfrontnet
      - mpdadmin
  # ------ mpcontainer-pyapp ------
  mpcpyapp:
    build:
      context: ./container-pyapp/
      cache_from:
        - python:3-slim-buster
    container_name: mpcpyapp
    environment:
      - TZ=UTC
      - env_mpypyapp_envtest=docker_compose
    cap_drop:
      - net_bind_service
      - chown
      - dac_override
      - fsetid
      - setgid
    expose:
      - "8888"
    networks:
      - webfrontnet
      - mpdadmin

networks:
  webfrontnet:
    driver: bridge
  webfrontmpd:
    driver: bridge
  mpdadmin:
    driver: bridge
