apiVersion: v1
kind: Service
metadata:
  labels:
    mp.service: mpcpyapp
  name: mpcpyapp
  namespace: musicplayer
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    mp.service: mpcpyapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mp.service: mpcpyapp
  name: mpcpyapp
  namespace: musicplayer
spec:
  replicas: 1
  selector:
    matchLabels:
      mp.service: mpcpyapp
  strategy: {}
  template:
    metadata:
      labels:
        mp.network/webfrontnet: "true"
        mp.service: mpcpyapp
    spec:
      containers:
      - image: crgm/mpcontainer-pyapp:latest
        imagePullPolicy: "Always"
        name: mpcpyapp
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        env:
          - name: env_mpypyapp_envtest
            value: "kubernetes_default"
      restartPolicy: Always
      serviceAccountName: ""
