apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-claim
  namespace: musicplayer
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: slow
  resources:
    requests:
      storage: 12T
  selector:
    matchLabels:
      type: "music"
