apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-claim
  namespace: musicplayer
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "music"