name: linting

on:

  push:
    branches: [ master ]
    paths:
      - 'dev-vm/ansible-playbook.yml'
      - 'linode/ansible-playbook.yml'

  pull_request:
    branches: [ master ]
    paths:
      - 'dev-vm/ansible-playbook.yml'
      - 'linode/ansible-playbook.yml'

jobs:

  static-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # check ansible
    - name: lint_ansible_playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          dev-vm/ansible-playbook.yml
          linode/ansible-playbook.yml
        # ignore checks: long lines, compare true/false
        args: "-x 601,204"
