name: linting actions

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  static-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # check ansible
    - name: lint ansible playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          dev-vm/ansible-playbook.yml
          linode/ansible-playbook.yml
        # ignore checks: long lines, compare true/false
        args: "-x 601,204"
