# Github Actions

name: MPContainer CI lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  staticcheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: lint the ansible
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          dev-vm/ansible-playbook.yml
          linode/ansible-playbook.yml
        # ignore checks: long lines, compare true/false
        args: "-x 601,204"
