# Github Actions

name: MPContainer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  staticcheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: lint the ansible
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          dev-vm/ansible-playbook.yml
          linode/ansible-playbook.yml
        args: "-x 601,204"
