name: security scans

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  static-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: terraform-security-sca
      uses: triat/terraform-security-scan@v1
      with:
        tfsec_actions_working_dir: "linode/terraform/lke/"